# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "this is job1"
        

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2 multi 
        run: |
          echo "this is job2 one"
          echo "this is job2 two"


  
